In [5]:
import sys
print(sys.executable)

/usr/local/bin/python3

In [6]:
import pandas as pd
import numpy as np

In [7]:
data_dict = pd.read_csv('data/data_dictionary.csv')
dim_month = pd.read_csv('data/dim_month.csv')
dim_plan = pd.read_csv('data/dim_plan.csv')
dim_user = pd.read_csv('data/dim_user.csv')
ft = pd.read_csv('data/fact_user_month.csv')

In [8]:
data_dict.head(5)

,table,field,description
0,fact_user_month,month,Month start date (YYYY-MM-01). Grain: user_id ...
1,fact_user_month,user_id,Unique user/account id.
2,fact_user_month,plan_id,FK to dim_plan. Plan active during the month.
3,fact_user_month,seats,Seat count for Team/Enterprise accounts.
4,fact_user_month,is_active,"1 if account active this month, else 0."

In [9]:
dim_month.head(5)

        month month_start   month_end  year  month_num month_name
0  2025-01-01  2025-01-01  2025-01-31  2025          1        Jan
1  2025-02-01  2025-02-01  2025-02-28  2025          2        Feb
2  2025-03-01  2025-03-01  2025-03-31  2025          3        Mar
3  2025-04-01  2025-04-01  2025-04-30  2025          4        Apr
4  2025-05-01  2025-05-01  2025-05-31  2025          5        May

In [10]:
dim_plan.head(10)

   plan_id   plan_name  base_price  included_seats  seat_price
0        1        Free         0.0               1         0.0
1        2         Pro        20.0               1         0.0
2        3        Team        60.0               3        12.0
3        4  Enterprise       250.0              10        25.0

In [11]:
dim_user.head(10)

,user_id,signup_date,acquisition_channel,country,account_type,initial_plan_id,first_project_date,first_deploy_date
0,1,2024-10-01,Referral,US,Individual,1,NaN,NaN
1,2,2024-10-01,Referral,IN,Individual,1,2024-10-08,2024-10-10
2,3,2024-10-01,Paid Search,DE,Individual,2,NaN,NaN
3,4,2024-10-01,Organic,GB,Individual,2,NaN,NaN
4,5,2024-10-01,Organic,US,Individual,1,NaN,NaN
5,6,2024-10-01,Organic,CA,Individual,1,2024-10-11,2024-10-20
6,7,2024-10-01,Referral,DE,Individual,1,2024-10-04,2024-10-06
7,8,2024-10-01,Paid Search,CA,Individual,1,NaN,2024-10-18
8,9,2024-10-01,Referral,FR,Team,2,NaN,NaN
9,10,2024-10-01,Organic,US,Team,1,2024-10-07,2024-10-14

In [12]:
ft.head(10)

,month,user_id,plan_id,seats,is_active,is_paying,mrr,new_paid,expansion_mrr,contraction_mrr,churn_mrr,churned_this_month,activation_within_7d,usage_events,deploys,projects_created
0,2025-01-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,1,0,5,0,0
1,2025-02-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
2,2025-03-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
3,2025-04-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
4,2025-05-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
5,2025-06-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
6,2025-07-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
7,2025-08-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
8,2025-09-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0
9,2025-10-01,1,1,1,0,0,0.0,0,0.0,0.0,0.0,0,0,0,0,0

In [13]:
# merge the dim_user table
df = pd.merge(ft, dim_user, how="left", on="user_id")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23570 entries, 0 to 23569
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   month                 23570 non-null  object
 1   user_id               23570 non-null  int64
 2   plan_id               23570 non-null  int64
 3   seats                 23570 non-null  int64
 4   is_active             23570 non-null  int64
 5   is_paying             23570 non-null  int64
 6   mrr                   23570 non-null  float64
 7   new_paid              23570 non-null  int64
 8   expansion_mrr         23570 non-null  float64
 9   contraction_mrr       23570 non-null  float64
 10  churn_mrr             23570 non-null  float64
 11  churned_this_month    23570 non-null  int64
 12  activation_within_7d  23570 non-null  int64
 13  usage_events          23570 non-null  int64
 14  deploys               23570 non-null  int64
 15  projects_created      23570 non-null  int64
 16  signup_date           23570 non-null  object
 17  acquisition_channel   23570 non-null  object
 18  country               23570 non-null  object
 19  account_type          23570 non-null  object
 20  initial_plan_id       23570 non-null  int64
 21  first_project_date    16349 non-null  object
 22  first_deploy_date     9790 non-null   object
dtypes: float64(4), int64(12), object(7)
memory usage: 4.1+ MB

In [15]:
df = pd.merge(df, dim_plan, how ="left", on="plan_id")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23570 entries, 0 to 23569
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   month                 23570 non-null  object
 1   user_id               23570 non-null  int64
 2   plan_id               23570 non-null  int64
 3   seats                 23570 non-null  int64
 4   is_active             23570 non-null  int64
 5   is_paying             23570 non-null  int64
 6   mrr                   23570 non-null  float64
 7   new_paid              23570 non-null  int64
 8   expansion_mrr         23570 non-null  float64
 9   contraction_mrr       23570 non-null  float64
 10  churn_mrr             23570 non-null  float64
 11  churned_this_month    23570 non-null  int64
 12  activation_within_7d  23570 non-null  int64
 13  usage_events          23570 non-null  int64
 14  deploys               23570 non-null  int64
 15  projects_created      23570 non-null  int64
 16  signup_date           23570 non-null  object
 17  acquisition_channel   23570 non-null  object
 18  country               23570 non-null  object
 19  account_type          23570 non-null  object
 20  initial_plan_id       23570 non-null  int64
 21  first_project_date    16349 non-null  object
 22  first_deploy_date     9790 non-null   object
 23  plan_name             23570 non-null  object
 24  base_price            23570 non-null  float64
 25  included_seats        23570 non-null  int64
 26  seat_price            23570 non-null  float64
dtypes: float64(6), int64(13), object(8)
memory usage: 4.9+ MB

In [17]:
df.describe()

,user_id,plan_id,seats,is_active,is_paying,mrr,new_paid,expansion_mrr,contraction_mrr,churn_mrr,churned_this_month,activation_within_7d,usage_events,deploys,projects_created,initial_plan_id,base_price,included_seats,seat_price
count,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000,23570.000000
mean,1109.715189,1.491515,1.572210,0.727662,0.372932,11.424777,0.009249,0.374120,0.116249,0.503606,0.047094,0.083920,12.449088,0.653161,0.709758,1.448197,12.335596,1.241621,1.423886
std,742.615706,0.699211,1.262413,0.445172,0.483594,23.735325,0.095728,3.752771,2.063293,5.637840,0.211844,0.277274,14.258774,1.029572,1.133041,0.692089,20.642575,0.693550,3.917831
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,492.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
50%,997.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,1642.000000,2.000000,1.000000,1.000000,1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000,1.000000,1.000000,2.000000,20.000000,1.000000,0.000000
max,3000.000000,4.000000,12.000000,1.000000,1.000000,250.000000,1.000000,190.000000,76.000000,250.000000,1.000000,1.000000,93.000000,9.000000,11.000000,3.000000,250.000000,10.000000,25.000000

In [18]:
df.head(5)

,month,user_id,plan_id,seats,is_active,is_paying,mrr,new_paid,expansion_mrr,contraction_mrr,...,acquisition_channel,country,account_type,initial_plan_id,first_project_date,first_deploy_date,plan_name,base_price,included_seats,seat_price
0,2025-01-01,1,1,1,0,0,0.0,0,0.0,0.0,...,Referral,US,Individual,1,NaN,NaN,Free,0.0,1,0.0
1,2025-02-01,1,1,1,0,0,0.0,0,0.0,0.0,...,Referral,US,Individual,1,NaN,NaN,Free,0.0,1,0.0
2,2025-03-01,1,1,1,0,0,0.0,0,0.0,0.0,...,Referral,US,Individual,1,NaN,NaN,Free,0.0,1,0.0
3,2025-04-01,1,1,1,0,0,0.0,0,0.0,0.0,...,Referral,US,Individual,1,NaN,NaN,Free,0.0,1,0.0
4,2025-05-01,1,1,1,0,0,0.0,0,0.0,0.0,...,Referral,US,Individual,1,NaN,NaN,Free,0.0,1,0.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23570 entries, 0 to 23569
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   month                 23570 non-null  object
 1   user_id               23570 non-null  int64
 2   plan_id               23570 non-null  int64
 3   seats                 23570 non-null  int64
 4   is_active             23570 non-null  int64
 5   is_paying             23570 non-null  int64
 6   mrr                   23570 non-null  float64
 7   new_paid              23570 non-null  int64
 8   expansion_mrr         23570 non-null  float64
 9   contraction_mrr       23570 non-null  float64
 10  churn_mrr             23570 non-null  float64
 11  churned_this_month    23570 non-null  int64
 12  activation_within_7d  23570 non-null  int64
 13  usage_events          23570 non-null  int64
 14  deploys               23570 non-null  int64
 15  projects_created      23570 non-null  int64
 16  signup_date           23570 non-null  object
 17  acquisition_channel   23570 non-null  object
 18  country               23570 non-null  object
 19  account_type          23570 non-null  object
 20  initial_plan_id       23570 non-null  int64
 21  first_project_date    16349 non-null  object
 22  first_deploy_date     9790 non-null   object
 23  plan_name             23570 non-null  object
 24  base_price            23570 non-null  float64
 25  included_seats        23570 non-null  int64
 26  seat_price            23570 non-null  float64
dtypes: float64(6), int64(13), object(8)
memory usage: 4.9+ MB

In [20]:
df = pd.merge(df, dim_month, how="left", on="month")

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23570 entries, 0 to 23569
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   month                 23570 non-null  datetime64[ns]
 1   user_id               23570 non-null  int64
 2   plan_id               23570 non-null  int64
 3   seats                 23570 non-null  int64
 4   is_active             23570 non-null  int64
 5   is_paying             23570 non-null  int64
 6   mrr                   23570 non-null  float64
 7   new_paid              23570 non-null  int64
 8   expansion_mrr         23570 non-null  float64
 9   contraction_mrr       23570 non-null  float64
 10  churn_mrr             23570 non-null  float64
 11  churned_this_month    23570 non-null  int64
 12  activation_within_7d  23570 non-null  int64
 13  usage_events          23570 non-null  int64
 14  deploys               23570 non-null  int64
 15  projects_created      23570 non-null  int64
 16  signup_date           23570 non-null  datetime64[ns]
 17  acquisition_channel   23570 non-null  object
 18  country               23570 non-null  object
 19  account_type          23570 non-null  object
 20  initial_plan_id       23570 non-null  int64
 21  first_project_date    16349 non-null  datetime64[ns]
 22  first_deploy_date     9790 non-null   datetime64[ns]
 23  plan_name             23570 non-null  object
 24  base_price            23570 non-null  float64
 25  included_seats        23570 non-null  int64
 26  seat_price            23570 non-null  float64
 27  month_start           23570 non-null  datetime64[ns]
 28  month_end             23570 non-null  datetime64[ns]
 29  year                  23570 non-null  int64
 30  month_num             23570 non-null  int64
 31  month_name            23570 non-null  object
dtypes: datetime64[ns](6), float64(6), int64(15), object(5)
memory usage: 5.8+ MB

In [29]:
df.to_csv('data/joined_data.csv', index=False)

In [30]:
explore = pd.read_csv('data/joined_data.csv')

In [31]:
explore.isnull().any()

month                   False
user_id                 False
plan_id                 False
seats                   False
is_active               False
is_paying               False
mrr                     False
new_paid                False
expansion_mrr           False
contraction_mrr         False
churn_mrr               False
churned_this_month      False
activation_within_7d    False
usage_events            False
deploys                 False
projects_created        False
signup_date             False
acquisition_channel     False
country                 False
account_type            False
initial_plan_id         False
first_project_date       True
first_deploy_date        True
plan_name               False
base_price              False
included_seats          False
seat_price              False
month_start             False
month_end               False
year                    False
month_num               False
month_name              False
dtype: bool

In [32]:
explore.head(5)

,month,user_id,plan_id,seats,is_active,is_paying,mrr,new_paid,expansion_mrr,contraction_mrr,...,first_deploy_date,plan_name,base_price,included_seats,seat_price,month_start,month_end,year,month_num,month_name
0,2025-01-01,1,1,1,0,0,0.0,0,0.0,0.0,...,NaN,Free,0.0,1,0.0,2025-01-01,2025-01-31,2025,1,Jan
1,2025-02-01,1,1,1,0,0,0.0,0,0.0,0.0,...,NaN,Free,0.0,1,0.0,2025-02-01,2025-02-28,2025,2,Feb
2,2025-03-01,1,1,1,0,0,0.0,0,0.0,0.0,...,NaN,Free,0.0,1,0.0,2025-03-01,2025-03-31,2025,3,Mar
3,2025-04-01,1,1,1,0,0,0.0,0,0.0,0.0,...,NaN,Free,0.0,1,0.0,2025-04-01,2025-04-30,2025,4,Apr
4,2025-05-01,1,1,1,0,0,0.0,0,0.0,0.0,...,NaN,Free,0.0,1,0.0,2025-05-01,2025-05-31,2025,5,May

In [26]:
explore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23570 entries, 0 to 23569
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   month                 23570 non-null  object
 1   user_id               23570 non-null  int64
 2   plan_id               23570 non-null  int64
 3   seats                 23570 non-null  int64
 4   is_active             23570 non-null  int64
 5   is_paying             23570 non-null  int64
 6   mrr                   23570 non-null  float64
 7   new_paid              23570 non-null  int64
 8   expansion_mrr         23570 non-null  float64
 9   contraction_mrr       23570 non-null  float64
 10  churn_mrr             23570 non-null  float64
 11  churned_this_month    23570 non-null  int64
 12  activation_within_7d  23570 non-null  int64
 13  usage_events          23570 non-null  int64
 14  deploys               23570 non-null  int64
 15  projects_created      23570 non-null  int64
 16  signup_date           23570 non-null  object
 17  acquisition_channel   23570 non-null  object
 18  country               23570 non-null  object
 19  account_type          23570 non-null  object
 20  initial_plan_id       23570 non-null  int64
 21  first_project_date    16349 non-null  object
 22  first_deploy_date     9790 non-null   object
 23  plan_name             23570 non-null  object
 24  base_price            23570 non-null  float64
 25  included_seats        23570 non-null  int64
 26  seat_price            23570 non-null  float64
 27  month_start           23570 non-null  object
 28  month_end             23570 non-null  object
 29  year                  23570 non-null  int64
 30  month_num             23570 non-null  int64
 31  month_name            23570 non-null  object
dtypes: float64(6), int64(15), object(11)
memory usage: 5.8+ MB

In [33]:
dates = ['month','month_start', 'month_end', 'signup_date', 'first_project_date', 'first_deploy_date']

for x in dates:
    explore[x] = pd.to_datetime(df[x])

# Investigation Framework

## Step 1: Anchor the Narrative

**Question:** Is MRR trending up, flat, or slowing?

### Action

* Calculate total MRR by month.
* Plot the trend.

### Output

* Growth rate by month
* Month-over-month change


## Step 2: Segment by Plan

Segment by:

* Month
* Plan type

### Analyze

* MRR by plan over time
* Churn rate by plan
* NRR by plan
* ARPU by plan

### Questions

* Is Pro growing faster than Free?
* Is Premium shrinking while Free grows?
* Is ARPU compressing?
* Is churn concentrated in one plan?

### Risk Signals

* Growth concentrated in lower-priced plans → Margin compression risk
* High churn in one tier → Pricing/packaging issue

---

## Step 3: Segment by Activation

Segment by:

* activation_within_7d (Yes / No / Unknown)
* Month

### Calculate

* Churn rate by activation status
* NRR by activation status
* Revenue contribution by activation segment

### Interpretation

If:

* Activated users → 120% NRR
* Non-activated users → 70% NRR

Then:

Revenue durability is concentrated in activated users.

That is not a metric.
That is a strategic lever.

---

## Step 4: Segment by Account Age

Create mutually exclusive buckets:

* 0–1 months
* 2–6 months
* 6+ months

### Analyze

* Churn rate by age bucket
* NRR by age bucket
* Revenue contribution by age bucket

### Questions

* Is churn front-loaded?
* Are mature users stable?
* Are recent cohorts retaining worse than older ones?

### Structural vs Noise

* Recent cohort degradation → Structural issue
* One-month anomaly → Likely noise

---

## Step 5: Revenue Bridge Analysis

For each month calculate:

Starting MRR

* Expansion
  − Contraction
  − Churn
  = Ending MRR

### Purpose

Identify the driver of revenue movement:

* Is decline caused by churn?
* Is downgrade behavior increasing?
* Is expansion slowing?

### Output

* Monthly revenue bridge table
* Contribution breakdown (% of total movement)

### Executive Insight Example

If:
Churn + downgrades > expansion

Then:

Revenue durability is weak.

---

## Step 6: Cohort Retention Matrix

Build:

* Logo retention by cohort
* Revenue retention by cohort

### Questions

* Are newer cohorts weaker?
* Are specific signup months underperforming?
* Is retention improving or degrading over time?

This distinguishes structural shifts from volatility.

---

In [40]:
explore.columns

Index(['month', 'user_id', 'plan_id', 'seats', 'is_active', 'is_paying', 'mrr',
       'new_paid', 'expansion_mrr', 'contraction_mrr', 'churn_mrr',
       'churned_this_month', 'activation_within_7d', 'usage_events', 'deploys',
       'projects_created', 'signup_date', 'acquisition_channel', 'country',
       'account_type', 'initial_plan_id', 'first_project_date',
       'first_deploy_date', 'plan_name', 'base_price', 'included_seats',
       'seat_price', 'month_start', 'month_end', 'year', 'month_num',
       'month_name'],
      dtype='object')

In [43]:
plans = explore[['plan_id', 'plan_name', 'base_price']]
plans.head(10)

   plan_id plan_name  base_price
0        1      Free         0.0
1        1      Free         0.0
2        1      Free         0.0
3        1      Free         0.0
4        1      Free         0.0
5        1      Free         0.0
6        1      Free         0.0
7        1      Free         0.0
8        1      Free         0.0
9        1      Free         0.0

In [51]:
print(plans['plan_name'].unique())
print(plans['plan_id'].unique())

['Free' 'Pro' 'Team' 'Enterprise']
[1 2 3 4]

In [54]:
# MMR  = subscription revenue earned each month from active paying subscribers.
# need total active paying subscribers
# plan costs for each tier
# total paid for each subscriber in each tier
# sum

total_active_users = explore[explore['is_active']== 1]['user_id'].nunique()
print('total active users: \n', total_active_users)
total_active_paying = explore[(explore['is_active']== 1) & (explore['plan_id'] != 1)]['user_id'].nunique()
print('total active paying: \n', total_active_paying)
total_free = explore[(explore['is_active']== 1) & (explore['plan_id'] == 1)]['user_id'].nunique()
print('total free: \n', total_free)
total_pro = explore[(explore['is_active']== 1) & (explore['plan_id'] == 2)]['user_id'].nunique()
print('total pro: \n', total_pro)
total_team = explore[(explore['is_active']== 1) & (explore['plan_id'] == 3)]['user_id'].nunique()
print('total team: \n', total_team)
total_enterprise = explore[(explore['is_active']== 1) & (explore['plan_id'] == 4)]['user_id'].nunique()
print('total enterprise: \n', total_enterprise)

total active users:
 2786
total active paying:
 1143
total free:
 1855
total pro:
 825
total team:
 352
total enterprise:
 3

In [56]:
churn = explore[['churned_this_month', 'is_active']]
churn

       churned_this_month  is_active
0                       1          0
1                       0          0
2                       0          0
3                       0          0
4                       0          0
...                   ...        ...
23565                   0          1
23566                   0          1
23567                   0          1
23568                   0          1
23569                   0          1

[23570 rows x 2 columns]

In [ ]:
total_active_users = explore[explore['is_active']== 1]['user_id'].nunique()
print('total active users: \n', total_active_users)
total_active_paying = explore[(explore['is_active']== 1) & (explore['plan_id'] != 1)]['user_id'].nunique()
print('total active paying: \n', total_active_paying)
total_free = explore[(explore['is_active']== 1) & (explore['plan_id'] == 1)]['user_id'].nunique()
print('total free: \n', total_free)
total_pro = explore[(explore['is_active']== 1) & (explore['plan_id'] == 2)]['user_id'].nunique()
print('total pro: \n', total_pro)
total_team = explore[(explore['is_active']== 1) & (explore['plan_id'] == 3)]['user_id'].nunique()
print('total team: \n', total_team)
total_enterprise = explore[(explore['is_active']== 1) & (explore['plan_id'] == 4)]['user_id'].nunique()
print('total enterprise: \n', total_enterprise)